'use client';
import {useState} from 'react';
import {createWalletClient,custom,parseUnits,type Address} from 'viem';
import {base} from 'viem/chains';

const USDC='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' as Address;
const erc20Abi=[{type:'function',name:'approve',stateMutability:'nonpayable',inputs:[{name:'spender',type:'address'},{name:'amount',type:'uint256'}],outputs:[{type:'bool'}]}] as const;
const paymentAbi=[{type:'function',name:'pay',stateMutability:'nonpayable',inputs:[{name:'linkId',type:'bytes32'},{name:'recipient',type:'address'},{name:'amount',type:'uint256'},{name:'memo',type:'string'}],outputs:[]}] as const;
declare global{interface Window{ethereum?:{request:(args:{method:string;params?:unknown[]})=>Promise<unknown>}}}

export default function Home(){
 const[address,setAddress]=useState<Address>(); const[amount,setAmount]=useState('1'); const[recipient,setRecipient]=useState(''); const[memo,setMemo]=useState('BasePayLink payment'); const[status,setStatus]=useState(''); const[tx,setTx]=useState('');
 const connect=async()=>{if(!window.ethereum){setStatus('Install MetaMask or another browser wallet.');return}try{const a=await window.ethereum.request({method:'eth_requestAccounts'}) as string[];setAddress(a[0] as Address);await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x2105'}]});setStatus('Wallet connected to Base Mainnet.')}catch(e){setStatus(e instanceof Error?e.message:'Connection failed.')}};
 const pay=async()=>{const contract=process.env.NEXT_PUBLIC_PAYMENT_CONTRACT as Address|undefined;if(!window.ethereum||!address){setStatus('Connect wallet first.');return}if(!contract){setStatus('Set NEXT_PUBLIC_PAYMENT_CONTRACT in .env.local');return}if(!/^0x[a-fA-F0-9]{40}$/.test(recipient)){setStatus('Enter a valid recipient address.');return}try{const w=createWalletClient({chain:base,transport:custom(window.ethereum)});const value=parseUnits(amount,6);setStatus('Approve USDC in your wallet...');await w.writeContract({address:USDC,abi:erc20Abi,functionName:'approve',args:[contract,value],account:address});setStatus('Approval sent. Confirm payment in your wallet...');const hash=await w.writeContract({address:contract,abi:paymentAbi,functionName:'pay',args:[('0x'+'0'.repeat(64)) as `0x${string}`,recipient as Address,value,memo],account:address});setTx(hash);setStatus('Payment submitted.');}catch(e){setStatus(e instanceof Error?e.message:'Payment failed.')}}
 return <main className="container"><div className="badge">BASE MAINNET</div><h1>BasePayLink</h1><p className="subtitle">Simple USDC payments powered by Base.</p><section className="card"><button onClick={connect}>{address?`${address.slice(0,6)}...${address.slice(-4)}`:'Connect Wallet'}</button></section><section className="card"><h2>Send USDC</h2><label>Recipient</label><input placeholder="0x..." value={recipient} onChange={e=>setRecipient(e.target.value)}/><label>Amount (USDC)</label><input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/><label>Memo</label><input value={memo} onChange={e=>setMemo(e.target.value)}/><button disabled={!address} onClick={pay}>Pay USDC</button>{status&&<p className="status">{status}</p>}{tx&&<p>Transaction: <a href={`https://basescan.org/tx/${tx}`} target="_blank">View on BaseScan</a></p>}</section></main>
}